### ISSUE TITLE
Cannot run it locally

### ISSUE THREAD

**Issue by sabativi** [kenshoo/react-multi-select#118]
## Expected Behavior

Modify source code to propose new version

## Actual Behavior

```
> @kenshooui/react-multi-select@0.0.0-development storybook /Users/sabativi/playground/react-multi-select
> start-storybook -p 6006

info @storybook/react v3.4.11
info
info => Loading custom .babelrc
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
/Users/sabativi/playground/react-multi-select/node_modules/webpack/lib/DefinePlugin.js:97
                compiler.hooks.compilation.tap(
                               ^

TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/Users/sabativi/playground/react-multi-select/node_modules/webpack/lib/DefinePlugin.js:97:18)
    at Compiler.apply (/Users/sabativi/playground/react-multi-select/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/sabativi/playground/react-multi-select/node_modules/@storybook/core/node_modules/webpack/lib/webpack.js:33:19)
    at exports.default (/Users/sabativi/playground/react-multi-select/node_modules/@storybook/core/dist/server/middleware.js:29:40)
    at buildDev (/Users/sabativi/playground/react-multi-select/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/Users/sabativi/playground/react-multi-select/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/sabativi/playground/react-multi-select/node_modules/@storybook/react/bin/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kenshooui/react-multi-select@0.0.0-development storybook: `start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kenshooui/react-multi-select@0.0.0-development storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sabativi/.npm/_logs/2018-12-17T08_21_52_461Z-debug.log 
```

## Steps to Reproduce the Problem

  1. git clone
  1. npm install
  1. npm run storybook

## Specifications

  - Version: node 10.14.1
  - Platform: MacOS 10.13

**Comment by liorheber** [comment]
@sabativi react-multi-select uses yarn.lock which means you need to use yarn to ensure that you are using the correct dependencies.
Could you please try installing the dependencies with yarn?
I will look into adding a package.lock to the project to support both.

**Comment by talyak** [comment]
@sabativi - Has the problem worked out for you? can I close this issue?

**Comment by sabativi** [comment]
Yes
